version: "3.9"

services:
  bot:
    environment:
      - DATABASE_GRPC_ADDR=database:50051
    ports:
      - "8080:8080"

  database:
    environment:
      - DATABASE_DSN=postgresql+psycopg://postgres:postgres@postgres:5432/pricebot
      - GRPC_PORT=50051
    ports:
      - "50051:50051"

  postgres:
    environment:
      - POSTGRES_DB=pricebot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

